version: "2"
services:
  web:
    build:
      context: .
    # environment:
      # - maildomain=postoq.com
      # - smtp_user=mailuser:mailpassword
    restart: always
    volumes:
      - $PWD:/var/www
    ports:
      - 8080:80
