version: "2"
services:
  web:
    build:
      context: .
    restart: always
    volumes:
      - $PWD:/var/www:z
    ports:
      - 8080:80
    environment:
      - COGNITO_DOMAIN=change_to
      - COGNITO_REGION_ID=your
      - COGNITO_USERPOOL_ID=userpool
      - COGNITO_CLIENT_ID=settings
