---
version: "2"
services:
  composer:
    image: composer
    volumes:
      - $PWD:/app
    command:
      - install
      - --ignore-platform-reqs
  web:
    build:
      context: .
    restart: always
    volumes:
      - $PWD:/var/www:z
    ports:
      - 8080:80
    environment:
      - COGNITO_DOMAIN=change_to
      - COGNITO_REGION_ID=your
      - COGNITO_USERPOOL_ID=userpool
      - COGNITO_CLIENT_ID=settings
      - COGNITO_CALLBACK_URL=http://localhost:8080/callback.php
    depends_on:
      - composer
